// <auto-generated />
namespace CleanCode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeofGenreidinttobyteinviewModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeofGenreidinttobyteinviewModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291710186_change of Genre id - int to byte in viewModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
